NO_CORE                = yes
ARDUINO_DIR            = /opt/arduino_HACKED/arduino
#BOARD                  = uno
BOARD                  = leonardo
TARGET                 = ask3_a
ARDUINO_LIBS           =
#MCU                    = atmega328p
MCU                    = atmega32u4
F_CPU                  = 16000000
ARDUINO_PORT           =
AVRDUDE_ARD_BAUDRATE   = 115200
AVRDUDE_ARD_PROGRAMMER = arduino

include /opt/arduino_HACKED/edam.mk
